# Generated by Django 5.0.3 on 2024-03-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('S', 'Superuser'), ('E', 'Employer'), ('C', 'Candidate')], default='S', max_length=1),
        ),
    ]
