# Generated by Django 5.0.3 on 2024-03-18 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('min_exp', models.FloatField(default=0)),
                ('max_exp', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('type_remote', models.CharField(blank=True, choices=[('R', 'Remote'), ('O', 'Office'), ('H', 'Hybrid')], max_length=1, null=True)),
                ('type_work', models.CharField(blank=True, choices=[('F', 'Full time'), ('P', 'Part time')], max_length=1, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('job_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
